### ISSUE TITLE
Header Color Section , color pallet not fully showing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/buri#3]
The color pallet for the following options in the Header Color Section does not show: 
Dropdown menu BG color : https://prnt.sc/uqhx75
Dropdown menu color : https://prnt.sc/uqhwy9
Dropdown menu hover color : https://prnt.sc/uqhw4k

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
