### ISSUE TITLE
404 Page color pallets not fully showing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/buri#4]
The color pallets that let's us customize the 404 Page are not fully appearing : 
404 Text 1 Color: https://prnt.sc/uqi080
404 Text 2 Color : https://prnt.sc/uqi0ej
404 Page Background Color: https://prnt.sc/uqi0pr

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
