### ISSUE TITLE
Footer page color pallet not fully showing 

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/buri#6]
If we to change the color on the following elements on the footer, we will not see the full color pallet : 
Footer Widget Title Color : https://prnt.sc/uqi9gl
Footer Anchor Color : https://prnt.sc/uqia0c
Footer Anchor Hover Color:  https://prnt.sc/uqiac5

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
